fragment userSettingsFragment on UserSettings {
  id
  communication {
    allowOtherUsersToSendMessages
    __typename
  }
  privacy {
    contributionRolesPubliclyVisible
    __typename
  }
  notification {
    platform {
      admin {
        userProfileRemoved {
          email
          inApp
          push
          __typename
        }
        userProfileCreated {
          email
          inApp
          push
          __typename
        }
        spaceCreated {
          email
          inApp
          push
          __typename
        }
        userGlobalRoleChanged {
          email
          inApp
          push
          __typename
        }
        __typename
      }
      forumDiscussionComment {
        email
        inApp
        push
        __typename
      }
      forumDiscussionCreated {
        email
        inApp
        push
        __typename
      }
      __typename
    }
    organization {
      adminMentioned {
        email
        inApp
        push
        __typename
      }
      adminMessageReceived {
        email
        inApp
        push
        __typename
      }
      __typename
    }
    space {
      admin {
        communityApplicationReceived {
          email
          inApp
          push
          __typename
        }
        collaborationCalloutContributionCreated {
          email
          inApp
          push
          __typename
        }
        communityNewMember {
          email
          inApp
          push
          __typename
        }
        communicationMessageReceived {
          email
          inApp
          push
          __typename
        }
        __typename
      }
      collaborationCalloutContributionCreated {
        email
        inApp
        push
        __typename
      }
      communicationUpdates {
        email
        inApp
        push
        __typename
      }
      collaborationCalloutPublished {
        email
        inApp
        push
        __typename
      }
      collaborationCalloutComment {
        email
        inApp
        push
        __typename
      }
      collaborationCalloutPostContributionComment {
        email
        inApp
        push
        __typename
      }
      communityCalendarEvents {
        email
        inApp
        push
        __typename
      }
      collaborationPollVoteCastOnOwnPoll {
        email
        inApp
        push
        __typename
      }
      collaborationPollVoteCastOnPollIVotedOn {
        email
        inApp
        push
        __typename
      }
      collaborationPollModifiedOnPollIVotedOn {
        email
        inApp
        push
        __typename
      }
      collaborationPollVoteAffectedByOptionChange {
        email
        inApp
        push
        __typename
      }
      __typename
    }
    user {
      membership {
        spaceCommunityInvitationReceived {
          email
          inApp
          push
          __typename
        }
        spaceCommunityJoined {
          email
          inApp
          push
          __typename
        }
        # spaceCommunityApplicationSubmitted {
        #   email
        #   inApp
        #   __typename
        # }
        __typename
      }
      mentioned {
        email
        inApp
        push
        __typename
      }
      commentReply {
        email
        inApp
        push
        __typename
      }
      messageReceived {
        email
        inApp
        push
        __typename
      }
      conversationMessageDirect {
        email
        inApp
        push
        __typename
      }
      conversationMessageGroup {
        email
        inApp
        push
        __typename
      }
      # copyOfMessageSent {
      #   email
      #   inApp
      #   __typename
      # }
      __typename
    }
    virtualContributor {
      adminSpaceCommunityInvitation {
        email
        inApp
        push
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}
