fragment CalloutDetails on Callout {
  id
  framing {
    id
    profile {
      id
      displayName
      description
      tagset {
        ...TagsetDetails
        __typename
      }
      references {
        ...ReferenceDetails
        __typename
      }
      storageBucket {
        id
        __typename
      }
      url
      __typename
    }
    type
    whiteboard {
      ...WhiteboardDetails
      __typename
    }
    __typename
  }
  contributionDefaults {
    id
    defaultDisplayName
    postDescription
    whiteboardContentAvailable
    __typename
  }
  sortOrder
  activity
  contributions {
    ...ContributionsData
  }
  comments {
    ...CommentsWithMessages
    __typename
  }
  authorization {
    id
    myPrivileges
    __typename
  }
  settings {
    ...CalloutSettingsFull
    __typename
  }
  __typename
}
