// spec: client-web/src/functional-e2e/plans/templates-test-plan.md#11a-whiteboard-template-crud-space-settings-library

import { expect } from '@playwright/test';
import { TestScenarioConfig, TestScenarioFactory, TestUser, TestUserManager } from '@alkemio/tests-lib';
import { createAuthenticatedSessionFixture } from '@src/functional-e2e/fixtures/authenticated-session.fixture';
import { OrganizationWithSpaceModel } from '@alkemio/tests-lib/scenario/models/OrganizationWithSpaceModel';
import { randomBytes } from 'crypto';
import { WhiteboardTemplateForm } from './forms/template-form.models';
import { fillWhiteboardTemplateForm, fillWhiteboardWithWhiteboardTemplate } from './forms/whiteboard-template-form';
import { verifyWhiteboardTemplate } from './verify/whiteboard-template-verify';
import { fillTemplateForm } from './forms/template-form';
import { verifyTemplate } from './verify/template-verify';


// Create the authenticated fixture with a unique storage state name for this test suite
const { test, setupAuthentication, teardownAuthentication } =
  createAuthenticatedSessionFixture({
    storageStateName: 'whiteboard-templates-test.json',
    cleanupAfterTests: process.env.cleanupAfterTests === 'true',
  });

const baseUrl = process.env.ALKEMIO_BASE_URL || 'http://localhost:3000';

let baseScenario: OrganizationWithSpaceModel;
const scenarioConfig: TestScenarioConfig = {
  name: 'whiteboard-template',
  space: {
    collaboration: {
      addTutorialCallouts: false,
    },
    community: {
      admins: [TestUser.SPACE_ADMIN],
      members: [
        TestUser.SPACE_MEMBER,
        TestUser.SPACE_ADMIN,
      ],
    },
  },
};

const templateData: WhiteboardTemplateForm = {
  displayName: 'Test Whiteboard Template',
  description: 'Use this template to facilitate collaborative whiteboard workshops with structured prompts.',
  tags: ['template', 'whiteboard'],
  textInWhiteboard: 'Whiteboard Template Generated by Playwright',
};

test.describe.serial('Whiteboard Templates', () => {
  test.beforeAll(async ({ browser, context }) => {
    baseScenario = await TestScenarioFactory.createBaseScenario(scenarioConfig);
    await setupAuthentication(browser, TestUserManager.users.spaceAdmin.email);
  });
  test.afterAll(async () => {
    // Clean up authentication
    await teardownAuthentication();
  });

  test.beforeEach(async ({ page }) => {
    await page.goto(`${baseUrl}/${baseScenario.space.nameId}/settings/templates`);

    // Verify we are on the Templates settings page
    await expect(page.getByText('Here you can create and edit Templates for this space.')).toBeVisible();
  });

  test('1.0 Navigate to templates settings', async ({
    page,
  }) => {
    // Navigate to the root of the space
    await page.goto(`${baseUrl}/${baseScenario.space.nameId}`);

    // Click Settings tab to access space settings
    await page.getByRole('tab', { name: 'Settings' }).click();

    // Click Templates tab to access template management
    await page.getByRole('tab', { name: 'Templates' }).click();

    // Verify we are on the Templates settings page
    await expect(page.url()).toMatch(/\/settings\/templates$/);
  });

  test('1.1 Create Whiteboard Template', async ({ page }) => {
    // Verify all template sections are visible
    await expect(page.getByRole('heading', { name: 'Whiteboard Templates' })).toBeVisible();

    // Find the container (parent of the parent of the heading) and then the "Create new" button within it
    const createNewButton = await page.getByRole('heading', { name: 'Whiteboard Templates' }).
      locator('..').locator('..').locator('..').
      getByRole('button', {name: 'Create New'});
    await createNewButton.click();

    // Wait for the Whiteboard Template creation dialog to appear
    await expect(page.getByRole('heading', { name: 'Create new Whiteboard Template' })).toBeVisible();

    // Fill the form:
    await fillWhiteboardTemplateForm(page, templateData);

    // Verify the Create button is enabled
    const createButton = page.getByRole('button', { name: 'Create' });
    await expect(createButton).toBeEnabled();

    // Click the Create button to save the Whiteboard Template
    await createButton.click();

    // Verify the dialog closes
    await expect(page.getByRole('heading', { name: 'Create new Whiteboard Template' })).not.toBeVisible();

    await verifyWhiteboardTemplate(page, templateData);
  });

  test('1.2 Edit Whiteboard Template', async ({ page }) => {
    const EditedTag = ' Edited-' + randomBytes(3).toString('hex');

    // Find the template title and click on it to open the template
    await page.getByRole('heading', { name: templateData.displayName }).click();

    await page.getByRole('button', { name: 'Edit' }).click();


    templateData.displayName = templateData.displayName + EditedTag;
    templateData.description = templateData.description + EditedTag;
    templateData.tags.push(EditedTag);
    templateData.textInWhiteboard = templateData.textInWhiteboard + EditedTag;


    // Wait for the edit dialog to appear
    await expect(page.getByRole('heading', { name: 'Edit Whiteboard Template' })).toBeVisible();

    await fillWhiteboardTemplateForm(page, templateData);


    // Click the Save button to save the changes
    const saveButton = page.getByRole('button', { name: 'Update' });
    await expect(saveButton).toBeEnabled();
    await saveButton.click();

    // Verify the dialog closes
    await expect(page.getByRole('heading', { name: 'Edit Whiteboard Template' })).not.toBeVisible();

    // Verify the data was updated
    await verifyWhiteboardTemplate(page, templateData);

    // Reload the page to ensure changes persist
    await page.reload();

    await verifyWhiteboardTemplate(page, templateData);
  });

  test('1.3 Use whiteboard template in a whiteboard', async ({ page }) => {
    // Verify all template sections are visible
    await expect(page.getByRole('heading', { name: 'Whiteboard Templates' })).toBeVisible();

    // Find the container (parent of the parent of the heading) and then the "Create new" button within it
    const createNewButton = await page.getByRole('heading', { name: 'Whiteboard Templates' }).
      locator('..').locator('..').locator('..').
      getByRole('button', { name: 'Create New' });
    await createNewButton.click();

    // Wait for the Whiteboard Template creation dialog to appear
    await expect(page.getByRole('heading', { name: 'Create new Whiteboard Template' })).toBeVisible();

    const testTemplate = {
      displayName: 'Whiteboard Template With template inside',
      description: 'This is a test, will not be saved.',
      tags: []
    }
    // Fill the form:
    await fillTemplateForm(page, testTemplate);

    await fillWhiteboardWithWhiteboardTemplate(page, templateData);

    await page.getByRole('button', { name: 'Create' }).click();

    await verifyTemplate(page, testTemplate);
  });

  test('1.4 Delete Whiteboard Template', async ({ page }) => {
    // Find the template title and click on it to open the template
    await page.getByRole('heading', { name: templateData.displayName }).click();

    await page.getByRole('button', { name: 'Edit', exact: true }).click();

    await page.getByRole('button', { name: 'Delete', exact: true }).click();

    await expect(page.getByText(`Are you sure you want to delete the Template '${templateData.displayName}'?`, { exact: true })).toBeVisible();

    await page.getByRole('button', { name: 'Delete' }).click();

    await expect(page.getByRole('heading', { name: 'Warning' })).not.toBeVisible();

    await expect(page.getByRole('heading', { name: 'Edit Whiteboard Template' })).not.toBeVisible();

    await expect(page.getByRole('heading', { name: templateData.displayName, exact: true })).not.toBeVisible();
  });
});
