export enum CalloutState {
  ARCHIVED = 'ARCHIVED',
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
}

export enum CalloutType {
  CANVAS = 'CANVAS',
  CARD = 'CARD',
  COMMENTS = 'COMMENTS',
}

export enum CalloutVisibility {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}

// export enum CalloutGroup {
//   KNOWLEDGE_GROUP_1 = 'KNOWLEDGE_GROUP_1',
//   KNOWLEDGE_GROUP_2 = 'KNOWLEDGE_GROUP_2',
//   DASHBOARD_GROUP_1 = 'DASHBOARD_GROUP_1',
//   DASHBOARD_GROUP_2 = 'DASHBOARD_GROUP_2',
//   CHALLENGES_GROUP_1 = 'CHALLENGES_GROUP_1',
//   CHALLENGES_GROUP_2 = 'CHALLENGES_GROUP_2',
//   COMMUNITY_GROUP_1 = 'COMMUNITY_GROUP_1',
//   COMMUNITY_GROUP_2 = 'COMMUNITY_GROUP_2',
// }
