query search($searchData: SearchInput!) {
  search(searchData: $searchData) {
    spaceResults {
      results {
        type
        ...SearchResultSpace
      }
      total
    }
    calloutResults {
      cursor
      results {
        id
        type

        terms
        ...SearchResultCallout
      }
      total
    }
    contributionResults {
      cursor
      results {
        id
        type

        terms
        ...SearchResultPost
        ...SearchResultCallout
      }
      total
    }
    contributorResults {
      cursor
      results {
        id
        type

        terms
        ...SearchResultUser
        ...SearchResultOrganization
      }
      total
    }
  }
}

fragment SearchResultSpace on SearchResultSpace {
  parentSpace {
    id
    level
    visibility
  }
  space {
    id
    level

    visibility
  }
}

fragment SearchResultCallout on SearchResultCallout {
  id
  callout {
    id
    type
    framing {
      id
      profile {
        id
        displayName
        description
        url
        tagset {
          ...TagsetDetails
        }
      }
    }
    contributionPolicy {
      id
      state
      allowedContributionTypes
    }
    contributions {
      id
      post {
        id
      }
      whiteboard {
        id
      }
      link {
        id
      }
    }
    comments {
      id
      messagesCount
    }
  }
  ...CalloutParent
}

fragment CalloutParent on SearchResultCallout {
  space {
    id
    level
  }
}

fragment SearchResultPost on SearchResultPost {
  post {
    id
    profile {
      id
      url
      displayName
      ...SearchResultPostProfile
    }
    createdBy {
      id
      profile {
        id
        displayName
      }
    }
    createdDate
    comments {
      id
      messagesCount
    }
  }
  ...PostParent
}

fragment SearchResultPostProfile on Profile {
  id
  description
  tagset {
    ...TagsetDetails
  }
}

fragment PostParent on SearchResultPost {
  space {
    id
    level
    visibility
  }
  callout {
    id
    framing {
      id
      profile {
        id
        url
        displayName
      }
    }
  }
}

fragment SearchResultUser on SearchResultUser {
  user {
    id
    isContactable
    profile {
      displayName
      ...SearchResultProfile
    }
  }
}

fragment SearchResultProfile on Profile {
  id
  description
  location {
    id
    country
    city
  }

  url
}

fragment SearchResultOrganization on SearchResultOrganization {
  organization {
    id
    profile {
      displayName
      ...SearchResultProfile
    }
  }
}
