query VirtualContributor($id: UUID!) {
  lookup {
    virtualContributor(ID: $id) {
      id
      nameID
      authorization {
        id
        myPrivileges
        __typename
      }

      account {
        id
        host {
          id
          profile {
            id
            displayName
            tagline
            avatar: visual(type: AVATAR) {
              uri
              __typename
            }
            location {
              id
              city
              country
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      settings {
        privacy {
          knowledgeBaseContentVisible
          __typename
        }
        __typename
      }
      provider {
        id
        profile {
          id
          displayName
          url
          location {
            country
            city
            __typename
          }
          avatar: visual(type: AVATAR) {
            ...VisualFull
            __typename
          }
          tagsets {
            id
            tags
            __typename
          }
          __typename
        }
        __typename
      }
      searchVisibility
      listedInStore
      status
      bodyOfKnowledgeID
      bodyOfKnowledgeType
      bodyOfKnowledgeDescription
      aiPersona {
        id
        engine
      }
      profile {
        id
        displayName
        description
        tagline
        tagsets {
          ...TagsetDetails
          __typename
        }
        url
        avatar: visual(type: AVATAR) {
          ...VisualFull
          __typename
        }
        references {
          id
          name
          uri
          description
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment VisualFull on Visual {
  id
  uri
  name
  allowedTypes
  aspectRatio
  maxHeight
  maxWidth
  minHeight
  minWidth
  alternativeText
  __typename
}

fragment TagsetDetails on Tagset {
  id
  name
  tags
  allowedValues
  type
  __typename
}
