mutation InviteForEntryRoleOnRoleSet(
  $roleSetId: UUID!
  $invitedActorIds: [UUID!]!
  $invitedUserEmails: [String!]!
  $welcomeMessage: String
  $extraRoles: [RoleName!]!
) {
  inviteForEntryRoleOnRoleSet(
    invitationData: {
      invitedActorIDs: $invitedActorIds
      invitedUserEmails: $invitedUserEmails
      roleSetID: $roleSetId
      welcomeMessage: $welcomeMessage
      extraRoles: $extraRoles
    }
  ) {
    type
    invitation {
      id
      state
      actor {
        id
        profile {
          id
          displayName
          __typename
        }
        __typename
      }
      __typename
    }
    platformInvitation {
      id
      email
      firstName
      lastName
      __typename
    }
    __typename
  }
}
