query GetTemplateById($templateId: UUID!) {
  lookup {
    template(ID: $templateId) {
      id
      type
      nameID
      profile {
        id
        displayName
        description
      }
      authorization {
        myPrivileges
      }
      contentSpace {
        id
        about {
          id
        }
        level
        subspaces {
          id
          about {
            id
          }
          level
          subspaces {
            id
            about {
              id
            }
            level
          }
        }
      }
      whiteboard {
        id
      }
      callout {
        id
      }
      postDefaultDescription
    }
  }
}
