query lookupProfileVisuals($ID: UUID!) {
  lookup {
    profile(ID: $ID) {
      description
      displayName
      storageBucket {
        authorization {
          myPrivileges
        }
        id
        parentEntity {
          displayName
          id
          type
          url
        }
        documents {
          id
          authorization {
            myPrivileges
          }
          displayName
          url
          createdBy {
            email
          }
        }
      }
      visuals {
        id
        name
        uri
        minWidth
        minHeight
        maxWidth
        maxHeight
        aspectRatio
        authorization {
          myPrivileges
        }
      }
    }
  }
}
