export enum ActivityLogs {
  CALLOUT_PUBLISHED = 'CALLOUT_PUBLISHED',
  CANVAS_CREATED = 'CANVAS_CREATED',
  CARD_COMMENT = 'CARD_COMMENT',
  CARD_CREATED = 'CARD_CREATED',
  DISCUSSION_COMMENT = 'DISCUSSION_COMMENT',
  MEMBER_JOINED = 'MEMBER_JOINED',
}
