// spec: client-web/src/functional-e2e/plans/templates-test-plan.md#11a-whiteboard-template-crud-space-settings-library

import { expect } from '@playwright/test';
import {
  TestScenarioConfig,
  TestScenarioFactory,
  TestUser,
  TestUserManager,
} from '@alkemio/tests-lib';
import { createAuthenticatedSessionFixture } from '@src/functional-e2e/fixtures/authenticated-session.fixture';
import { OrganizationWithSpaceModel } from '@alkemio/tests-lib/scenario/models/OrganizationWithSpaceModel';
import { randomBytes } from 'crypto';
import { WhiteboardTemplateForm } from './forms/template-form.models';
import {
  fillWhiteboardTemplateForm,
  fillWhiteboardWithWhiteboardTemplate,
} from './forms/whiteboard-template-form';
import { verifyWhiteboardTemplate } from './verify/whiteboard-template-verify';
import { fillTemplateForm } from './forms/template-form';
import { verifyOpenedTemplate } from './verify/verify-opened-template';
import { openWhiteboardTemplate } from './verify/open-template';

// Create the authenticated fixture with a unique storage state name for this test suite
const { test, setupAuthentication, teardownAuthentication } =
  createAuthenticatedSessionFixture({
    storageStateName: 'whiteboard-templates-test.json',
    cleanupAfterTests: process.env.cleanupAfterTests === 'true',
  });

const baseUrl = process.env.ALKEMIO_BASE_URL || 'http://localhost:3000';

let baseScenario: OrganizationWithSpaceModel;
const scenarioConfig: TestScenarioConfig = {
  name: 'whiteboard-template',
  space: {
    collaboration: {
      addTutorialCallouts: false,
    },
    community: {
      admins: [TestUser.SPACE_ADMIN],
      members: [TestUser.SPACE_MEMBER, TestUser.SPACE_ADMIN],
    },
  },
};

const templateData: WhiteboardTemplateForm = {
  displayName: 'Test Whiteboard Template',
  description:
    'Use this template to facilitate collaborative whiteboard workshops with structured prompts.',
  tags: ['template', 'whiteboard'],
  textInWhiteboard: 'Whiteboard Template Generated by Playwright',
};

test.describe.serial('Whiteboard Templates', () => {
  test.beforeAll(async ({ browser, context }) => {
    baseScenario = await TestScenarioFactory.createBaseScenario(scenarioConfig);
    await setupAuthentication(browser, TestUserManager.users.spaceAdmin.email);
  });
  test.afterAll(async () => {
    // Clean up authentication
    await teardownAuthentication();
   // await TestScenarioFactory.cleanUpBaseScenario(baseScenario);
  });

  test.beforeEach(async ({ page }) => {
    await page.goto(
      `${baseUrl}/${baseScenario.space.nameId}/settings/templates`
    );

    // Enable CRD feature flag and reload so the redesigned Templates page renders
    await page.evaluate(() => {
      localStorage.setItem('alkemio-crd-enabled', 'true');
    });
    await page.reload();

    // Verify we are on the Templates settings page
    await expect(
      page.getByRole('textbox', { name: 'Search templates…' })
    ).toBeVisible();
  });

  test('1.0 Navigate to templates settings', async ({ page }) => {
    // Navigate to the root of the space
    await page.goto(`${baseUrl}/${baseScenario.space.nameId}`);

    // Enable CRD feature flag
    await page.evaluate(() => {
      localStorage.setItem('alkemio-crd-enabled', 'true');
    });
    await page.reload();

    // Open space settings (now a link in the space banner, not a space tab)
    await page.getByRole('link', { name: 'Settings' }).click();

    // Click Templates tab to access template management
    await page.getByRole('tab', { name: 'Templates' }).click();

    // Verify we are on the Templates settings page
    await expect(page.url()).toMatch(/\/settings\/templates$/);
  });

  test('1.1 Create Whiteboard Template', async ({ page }) => {
    // Verify the Whiteboard templates section is visible
    await expect(
      page.getByRole('button', { name: /^Whiteboard templates/ })
    ).toBeVisible();

    // Open the "Add new" menu for the Whiteboard templates section (3rd section)
    await page.getByRole('button', { name: 'Add new' }).nth(2).click();
    await page.getByRole('menuitem', { name: 'Create new' }).click();

    // Wait for the Whiteboard Template creation dialog to appear
    const dialog = page.getByRole('dialog', {
      name: 'Create whiteboard template',
    });
    await expect(
      dialog.getByRole('heading', { name: 'Create whiteboard template' })
    ).toBeVisible();

    // Fill the form:
    await fillWhiteboardTemplateForm(page, templateData);

    // Verify the Save button is enabled
    const saveButton = dialog.getByRole('button', { name: 'Save' });
    await expect(saveButton).toBeEnabled();

    // Click the Save button to save the Whiteboard Template
    await saveButton.click();

    // Verify the dialog closes
    await expect(
      page.getByRole('heading', { name: 'Create whiteboard template' })
    ).not.toBeVisible();

    await verifyWhiteboardTemplate(page, templateData);
  });

  test('1.2 Edit Whiteboard Template', async ({ page }) => {
    const EditedTag = ' Edited-' + randomBytes(3).toString('hex');

    // Open the template's preview dialog, then start editing
    await page
      .getByRole('button', {
        name: `Preview: ${templateData.displayName}`,
        exact: true,
      })
      .click();
    await page.getByRole('button', { name: 'Edit template' }).click();

    templateData.displayName = templateData.displayName + EditedTag;
    templateData.description = templateData.description + EditedTag;
    templateData.tags.push(EditedTag);
    templateData.textInWhiteboard = templateData.textInWhiteboard + EditedTag;

    // Wait for the edit dialog to appear
    const dialog = page.getByRole('dialog', { name: 'Edit whiteboard template' });
    await expect(
      dialog.getByRole('heading', { name: 'Edit whiteboard template' })
    ).toBeVisible();

    await fillWhiteboardTemplateForm(page, templateData);

    // Click the Save button to save the changes
    const saveButton = dialog.getByRole('button', { name: 'Save' });
    await expect(saveButton).toBeEnabled();
    await saveButton.click();

    // Verify the dialog closes
    await expect(
      page.getByRole('heading', { name: 'Edit whiteboard template' })
    ).not.toBeVisible();

    // Verify the data was updated (re-opens and closes the preview dialog)
    await verifyWhiteboardTemplate(page, templateData);

    // Reload the page to ensure changes persist
    await page.reload();
    await verifyWhiteboardTemplate(page, templateData);
  });

  test('1.3 Use whiteboard template in a whiteboard', async ({ page }) => {
    // Verify the Whiteboard templates section is visible
    await expect(
      page.getByRole('button', { name: /^Whiteboard templates/ })
    ).toBeVisible();

    // Open the "Add new" menu for the Whiteboard templates section (3rd section)
    await page.getByRole('button', { name: 'Add new' }).nth(2).click();
    await page.getByRole('menuitem', { name: 'Create new' }).click();

    // Wait for the Whiteboard Template creation dialog to appear
    const dialog = page.getByRole('dialog', {
      name: 'Create whiteboard template',
    });
    await expect(
      dialog.getByRole('heading', { name: 'Create whiteboard template' })
    ).toBeVisible();

    const testTemplate = {
      displayName: 'Whiteboard Template With template inside',
      description: 'This is a test, will not be saved.',
      tags: [],
    };
    // Fill the form:
    await fillTemplateForm(page, testTemplate);

    await fillWhiteboardWithWhiteboardTemplate(page, templateData);

    await dialog.getByRole('button', { name: 'Save' }).click();
    await expect(
      page.getByRole('heading', { name: 'Create whiteboard template' })
    ).not.toBeVisible();

    await openWhiteboardTemplate(page, testTemplate);
    await verifyOpenedTemplate(page, testTemplate);
  });

  // test('1.4 Delete Whiteboard Template', async ({ page }) => {
  //   // Find the template title and click on it to open the template
  //   await page.getByRole('heading', { name: templateData.displayName }).click();

  //   await page.getByRole('button', { name: 'Edit', exact: true }).click();

  //   await page.getByRole('button', { name: 'Delete', exact: true }).click();

  //   await expect(
  //     page.getByText(
  //       `Are you sure you want to delete the Template '${templateData.displayName}'?`,
  //       { exact: true }
  //     )
  //   ).toBeVisible();

  //   await page.getByRole('button', { name: 'Delete' }).click();

  //   await expect(
  //     page.getByRole('heading', { name: 'Warning' })
  //   ).not.toBeVisible();

  //   await expect(
  //     page.getByRole('heading', { name: 'Edit Whiteboard Template' })
  //   ).not.toBeVisible();

  //   await expect(
  //     page.getByRole('heading', { name: templateData.displayName, exact: true })
  //   ).not.toBeVisible();
  // });
});
