import { Page, expect, Locator } from '@playwright/test';

export class CreateSpaceDialog {
  private dialog: Locator;

  constructor(private page: Page) {
    this.dialog = page.getByRole('dialog', { name: 'Create a new Space' });
  }

  // Form fields
  get titleInput() {
    return this.page.getByRole('textbox', { name: 'Title *' });
  }

  get urlInput() {
    return this.page.getByRole('textbox', { name: 'URL' });
  }

  get taglineInput() {
    return this.page.getByRole('textbox', { name: 'Tagline' });
  }

  get tagsCombobox() {
    return this.page.getByRole('combobox', { name: 'Tags' });
  }

  get tutorialsCheckbox() {
    return this.page.getByRole('checkbox', {
      name: 'Add Tutorials to this Space',
    });
  }

  get termsCheckbox() {
    return this.page.getByRole('checkbox', {
      name: 'I have read and accept the',
    });
  }

  get changeTemplateButton() {
    return this.page.getByRole('button', { name: 'Change Template' });
  }

  get uploadButtons() {
    return this.page.getByRole('button', { name: 'Upload' });
  }

  // Action buttons
  get createButton() {
    return this.page.getByRole('button', { name: 'Create' });
  }

  get cancelButton() {
    return this.page.getByRole('button', { name: 'Cancel' });
  }

  get closeButton() {
    return this.page.getByRole('button', { name: 'Close' });
  }

  // Character count indicator
  get urlCharacterCount() {
    return this.page.getByText(/\d+\s*\/\s*25/);
  }

  // Dialog visibility
  async isVisible(): Promise<boolean> {
    return await this.dialog.isVisible();
  }

  async waitForVisible() {
    await expect(this.dialog).toBeVisible();
  }

  async waitForHidden() {
    await expect(this.dialog).toBeHidden();
  }

  // Fill methods
  async fillTitle(title: string) {
    await this.titleInput.fill(title);
  }

  async fillUrl(url: string) {
    await this.urlInput.fill(url);
  }

  async fillTagline(tagline: string) {
    await this.taglineInput.fill(tagline);
  }

  async fillBasicInfo(title: string, url: string, tagline?: string) {
    await this.fillTitle(title);
    await this.fillUrl(url);
    if (tagline) {
      await this.fillTagline(tagline);
    }
  }

  // Checkbox methods
  async checkTutorials() {
    await this.tutorialsCheckbox.click();
  }

  async checkTerms() {
    await this.termsCheckbox.click();
  }

  async acceptTermsAndConditions() {
    await this.checkTerms();
  }

  // Verification methods
  async verifyCreateButtonEnabled() {
    await expect(this.createButton).toBeEnabled();
  }

  async verifyCreateButtonDisabled() {
    await expect(this.createButton).toBeDisabled();
  }

  async verifyTutorialsUnchecked() {
    await expect(this.tutorialsCheckbox).not.toBeChecked();
  }

  async verifyTutorialsChecked() {
    await expect(this.tutorialsCheckbox).toBeChecked();
  }

  async verifyTermsUnchecked() {
    await expect(this.termsCheckbox).not.toBeChecked();
  }

  async verifyAllFormElementsPresent() {
    await expect(this.changeTemplateButton).toBeVisible();
    await expect(this.titleInput).toBeVisible();
    await expect(this.urlInput).toBeVisible();
    await expect(this.taglineInput).toBeVisible();
    await expect(this.tagsCombobox).toBeVisible();
    await expect(this.uploadButtons.first()).toBeVisible();
    await expect(this.uploadButtons.nth(1)).toBeVisible();
    await expect(this.tutorialsCheckbox).toBeVisible();
    await expect(this.termsCheckbox).toBeVisible();
    await expect(this.cancelButton).toBeVisible();
    await expect(this.createButton).toBeVisible();
  }

  async verifyUrlAutoGenerated(expectedPattern: RegExp) {
    await expect(this.urlInput).toHaveValue(expectedPattern);
  }

  // Action methods
  async clickCreate() {
    await this.createButton.click();
  }

  async clickCancel() {
    await this.cancelButton.click();
  }

  async clickClose() {
    await this.closeButton.click();
  }

  async createSpace(
    title: string,
    url: string,
    options?: { tagline?: string; withTutorials?: boolean }
  ) {
    await this.fillBasicInfo(title, url, options?.tagline);

    if (options?.withTutorials) {
      await this.checkTutorials();
    }

    await this.acceptTermsAndConditions();
    await this.verifyCreateButtonEnabled();
    await this.clickCreate();
  }
}
