import { Page, expect, Locator } from '@playwright/test';

export class CreateSpaceDialog {
  private dialog: Locator;

  constructor(private page: Page) {
    // CRD renames the dialog from "Create a new Space" to "Create new Space".
    this.dialog = page.getByRole('dialog', { name: 'Create new Space' });
  }

  // Form fields (CRD renames "Title *" -> "Name *", keeps "URL *"/"Tagline").
  get titleInput() {
    return this.dialog.getByRole('textbox', { name: 'Name *' });
  }

  get urlInput() {
    return this.dialog.getByRole('textbox', { name: 'URL *' });
  }

  get taglineInput() {
    return this.dialog.getByRole('textbox', { name: 'Tagline' });
  }

  get tagsCombobox() {
    // CRD renders Tags as a free-text "press Enter to add" input, not a combobox.
    return this.dialog.getByRole('textbox', {
      name: 'Add a tag and press Enter',
    });
  }

  get tutorialsCheckbox() {
    return this.dialog.getByRole('checkbox', {
      name: 'Add Tutorials and example posts to this Space',
    });
  }

  get termsCheckbox() {
    return this.dialog.getByRole('checkbox', {
      name: 'I accept the terms and conditions for creating a Space.',
    });
  }

  get changeTemplateButton() {
    // CRD renames "Change Template" -> "Choose a template".
    return this.dialog.getByRole('button', { name: 'Choose a template' });
  }

  get uploadButtons() {
    // CRD names the two upload buttons explicitly.
    return this.dialog.getByRole('button', { name: /Upload .* banner/ });
  }

  // Action buttons
  get createButton() {
    // CRD renames "Create" -> "Create Space"; scoped to the dialog to avoid
    // colliding with the account page's own "Create Space" button.
    return this.dialog.getByRole('button', { name: 'Create Space' });
  }

  get cancelButton() {
    return this.dialog.getByRole('button', { name: 'Cancel' });
  }

  get closeButton() {
    // CRD renders the dialog dismiss control as an unnamed icon button; it is
    // the last button in the dialog. Fall back to Escape-equivalent click.
    return this.dialog.getByRole('button').last();
  }

  // Character count indicator
  get urlCharacterCount() {
    return this.page.getByText(/\d+\s*\/\s*25/);
  }

  // Dialog visibility
  async isVisible(): Promise<boolean> {
    return await this.dialog.isVisible();
  }

  async waitForVisible() {
    await expect(this.dialog).toBeVisible();
  }

  async waitForHidden() {
    await expect(this.dialog).toBeHidden({ timeout: 15_000 });
  }

  // Fill methods
  async fillTitle(title: string) {
    await this.titleInput.fill(title);
  }

  async fillUrl(url: string) {
    await this.urlInput.fill(url);
  }

  async fillTagline(tagline: string) {
    await this.taglineInput.fill(tagline);
  }

  async fillBasicInfo(title: string, url: string, tagline?: string) {
    await this.fillTitle(title);
    await this.fillUrl(url);
    if (tagline) {
      await this.fillTagline(tagline);
    }
  }

  // Checkbox methods
  async checkTutorials() {
    await this.tutorialsCheckbox.click();
  }

  async checkTerms() {
    await this.termsCheckbox.click();
  }

  async acceptTermsAndConditions() {
    await this.checkTerms();
  }

  // Verification methods
  async verifyCreateButtonEnabled() {
    await expect(this.createButton).toBeEnabled();
  }

  async verifyCreateButtonDisabled() {
    await expect(this.createButton).toBeDisabled();
  }

  async verifyTutorialsUnchecked() {
    await expect(this.tutorialsCheckbox).not.toBeChecked();
  }

  async verifyTutorialsChecked() {
    await expect(this.tutorialsCheckbox).toBeChecked();
  }

  async verifyTermsUnchecked() {
    await expect(this.termsCheckbox).not.toBeChecked();
  }

  async verifyAllFormElementsPresent() {
    await expect(this.changeTemplateButton).toBeVisible();
    await expect(this.titleInput).toBeVisible();
    await expect(this.urlInput).toBeVisible();
    await expect(this.taglineInput).toBeVisible();
    await expect(this.tagsCombobox).toBeVisible();
    await expect(this.uploadButtons.first()).toBeVisible();
    await expect(this.uploadButtons.nth(1)).toBeVisible();
    await expect(this.tutorialsCheckbox).toBeVisible();
    await expect(this.termsCheckbox).toBeVisible();
    await expect(this.cancelButton).toBeVisible();
    await expect(this.createButton).toBeVisible();
  }

  async verifyUrlAutoGenerated(expectedPattern: RegExp) {
    await expect(this.urlInput).toHaveValue(expectedPattern);
  }

  // Action methods
  async clickCreate() {
    await this.createButton.click();
  }

  async clickCancel() {
    await this.cancelButton.click();
    // CRD's Radix dialog occasionally needs a beat to dismiss; if it lingers,
    // fall back to Escape so the dialog reliably closes.
    if (await this.dialog.isVisible({ timeout: 2000 }).catch(() => false)) {
      await this.page.keyboard.press('Escape');
    }
  }

  async clickClose() {
    await this.closeButton.click();
    if (await this.dialog.isVisible({ timeout: 2000 }).catch(() => false)) {
      await this.page.keyboard.press('Escape');
    }
  }

  async createSpace(
    title: string,
    url: string,
    options?: { tagline?: string; withTutorials?: boolean }
  ) {
    await this.fillBasicInfo(title, url, options?.tagline);

    if (options?.withTutorials) {
      await this.checkTutorials();
    }

    await this.acceptTermsAndConditions();
    await this.verifyCreateButtonEnabled();
    await this.clickCreate();
  }
}
