mutation CreateTemplate(
  $templatesSetId: UUID!
  $profileData: CreateProfileInput!
  $type: TemplateType!
  $tags: [String!]
  $calloutData: CreateCalloutInput
  $communityGuidelinesData: CreateCommunityGuidelinesInput
  $contentSpaceData: CreateTemplateContentSpaceInput
  $postDefaultDescription: Markdown
  $whiteboard: CreateWhiteboardInput
  $includeProfileVisuals: Boolean = false
) {
  createTemplate(
    templateData: {
      templatesSetID: $templatesSetId
      profileData: $profileData
      tags: $tags
      type: $type
      calloutData: $calloutData
      communityGuidelinesData: $communityGuidelinesData
      postDefaultDescription: $postDefaultDescription
      contentSpaceData: $contentSpaceData
      whiteboard: $whiteboard
    }
  ) {
    id
    nameID
    type
    profile @include(if: $includeProfileVisuals) {
      id
      cardVisual: visual(type: CARD) {
        id
        __typename
      }
      previewVisual: visual(type: BANNER) {
        id
        __typename
      }
      __typename
    }
    callout {
      id
      framing {
        id
        whiteboard {
          id
          nameID
          profile {
            id
          }
        }
      }
    }
  }
}
