mutation CreateTemplateFromSpace(
  $templatesSetId: UUID!
  $profileData: CreateProfileInput!
  $tags: [String!]
  $spaceId: UUID!
) {
  createTemplateFromSpace(
    templateData: {
      templatesSetID: $templatesSetId
      profileData: $profileData
      tags: $tags
      spaceID: $spaceId
    }
  ) {
    id
    type
    profile {
      displayName
    }
    authorization {
      myPrivileges
    }
    contentSpace {
      id
      about {
        id
      }
      collaboration {
        id
        isTemplate
      }
      level
    }
  }
}
