mutation CreateVirtualContributorOnAccount(
  $virtualContributorData: CreateVirtualContributorOnAccountInput!
) {
  createVirtualContributor(virtualContributorData: $virtualContributorData) {
    id
    profile {
      id
      url
      __typename
    }
    aiPersona {
      engine
    }
    knowledgeBase {
      id
      calloutsSet {
        id
        authorization {
          myPrivileges
        }
        callouts {
          id
          framing {
            id
            profile {
              id
              displayName
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
