mutation CreateTemplateFromSpace(
  $templatesSetId: UUID!
  $profileData: CreateProfileInput!
  $tags: [String!]
  $spaceId: UUID!
  $recursive: Boolean
) {
  createTemplateFromSpace(
    templateData: {
      templatesSetID: $templatesSetId
      profileData: $profileData
      tags: $tags
      spaceID: $spaceId
      recursive: $recursive
    }
  ) {
    id
    type
    profile {
      displayName
    }
    authorization {
      myPrivileges
    }
    contentSpace {
      id
      about {
        id
      }
      collaboration {
        id
        isTemplate
      }
      level
      subspaces {
        id
        about {
          id
        }
        level
        subspaces {
          id
          about {
            id
          }
          level
        }
      }
    }
  }
}
