mutation UpdateUserSettings($settingsData: UpdateUserSettingsInput!) {
  updateUserSettings(settingsData: $settingsData) {
    id
    settings {
      ...userSettingsFragment
      __typename
    }
    __typename
    authorization {
      myPrivileges
    }
  }
}

# fragment userSettingsFragment on UserSettings {
#   id
#   communication {
#     allowOtherUsersToSendMessages
#     __typename
#   }
#   privacy {
#     contributionRolesPubliclyVisible
#     __typename
#   }
#   notification {
#     platform {
#       userProfileRemoved
#       newUserSignUp
#       forumDiscussionComment
#       forumDiscussionCreated
#       spaceCreated
#       __typename
#     }
#     organization {
#       mentioned
#       messageReceived
#       __typename
#     }
#     space {
#       communityApplicationReceived
#       communityApplicationSubmitted
#       communityInvitationUser
#       communityNewMember
#       communityNewMemberAdmin
#       communicationUpdates
#       communicationUpdatesAdmin
#       communicationMessage
#       communicationMessageAdmin
#       collaborationPostCommentCreated
#       collaborationCalloutPublished
#       collaborationPostCreated
#       collaborationPostCreatedAdmin
#       collaborationWhiteboardCreated
#       __typename
#     }
#     user {
#       mentioned
#       commentReply
#       messageReceived
#       messageSent
#       __typename
#     }
#     __typename
#   }
#   __typename
# }
