fragment TemplatesSetData on TemplatesSet {
  id
  spaceTemplates {
    ...TemplateProfileData
    ...SpaceTemplateData
  }
  postTemplates {
    ...TemplateProfileData
    ...PostTemplateData
  }
  whiteboardTemplates {
    ...TemplateProfileData
    ...WhiteboardTemplateData
  }
  communityGuidelinesTemplates {
    ...TemplateProfileData
    ...CommunityGuidelinesTemplateData
  }
  calloutTemplates {
    ...TemplateProfileData
    ...CalloutTemplateData
  }
  authorization {
    myPrivileges
  }
}
