query search($searchData: SearchInput!) {
  search(searchData: $searchData) {
    spaceResults {
      results {
        type
        ...SearchResultSpace
      }
    }
    calloutResults {
      results {
        type
        ...SearchResultCallout
      }
    }
    contributionResults {
      results {
        type
        ...SearchResultPost
        ...SearchResultCallout
      }
    }
    actorResults {
      results {
        type
        ...SearchResultUser
        ...SearchResultOrganization
      }
    }
  }
}

fragment SearchResultSpace on SearchResultSpace {
  parentSpace {
    id
    level
    visibility
  }
  space {
    id
    level
    visibility
  }
}

fragment SearchResultCallout on SearchResultCallout {
  id
  callout {
    id
    framing {
      id
      profile {
        id
        displayName
      }
    }
    contributions {
      id
      post {
        id
      }
      whiteboard {
        id
      }
      link {
        id
      }
    }
  }
  ...CalloutParent
}

fragment CalloutParent on SearchResultCallout {
  space {
    id
    level
  }
}

fragment SearchResultPost on SearchResultPost {
  post {
    id
    profile {
      displayName
      ...SearchResultPostProfile
    }
  }
  ...PostParent
}

fragment SearchResultPostProfile on Profile {
  displayName
}

fragment PostParent on SearchResultPost {
  space {
    id
    level
    visibility
  }
  callout {
    id
    framing {
      profile {
        displayName
      }
    }
  }
}

fragment SearchResultUser on SearchResultUser {
  user {
    id
    profile {
      displayName
    }
  }
}

fragment SearchResultProfile on Profile {
  id
  description
  location {
    id
    country
    city
  }

  url
}

fragment SearchResultOrganization on SearchResultOrganization {
  organization {
    id
    profile {
      displayName
    }
  }
}
