fragment SubspaceData on Space {
  id
  nameID
  level
  about {
    ...SpaceAboutDetails
  }
  collaboration {
    ...CollaborationData
  }
  authorization {
    ...AuthorizationData
  }
  community {
    ...CommunityData
  }
  settings {
    ...SettingsData
  }
  subspaces {
    id
    nameID
    level
    about {
      ...SpaceAboutDetails
    }
    collaboration {
      ...CollaborationData
    }
    authorization {
      ...AuthorizationData
    }
    community {
      ...CommunityData
    }
    settings {
      ...SettingsData
    }
  }
}
