name: Manual Clean Up Environment and Trigger Tests

on:
  workflow_dispatch:

jobs:
  cleanup-db:
    uses: ./.github/workflows/cleanup-database.yml
    with:
      postgres_db: alkemio
    secrets: inherit

  trigger-e2e-tests-travis-ci:
    needs: cleanup-db
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e Tests
        uses: cmdbg/travis-ci-action@main
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          TARGET_REPOSITORY: alkem-io/test-suites
          TARGET_BRANCH: develop
