name: Nightly Clean Up Environment and Trigger Tests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  cleanup-db:
    uses: ./.github/workflows/cleanup-database.yml
    with:
      postgres_db: alkemio
    secrets: inherit

  deploy-all-services:
    needs: cleanup-db
    uses: ./.github/workflows/deploy-all-services.yml
    secrets: inherit

  trigger-e2e-tests-travis-ci:
    needs: deploy-all-services
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e Tests
        uses: cmdbg/travis-ci-action@main
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          TARGET_REPOSITORY: alkem-io/test-suites
          TARGET_BRANCH: develop
